version: 1.0.{build}
build_script:
  - cmd: mvn clean install
test: off
artifacts:
  - path: target/*.jar
    name: Executable JAR

  - path: src/main/resources/application.properties
    name: Configuration file
