version: 1.0.{build}
build_script:
  - cmd: mvn clean install -Dmaven.test.skip=true
test: off
artifacts:
  - path: target/*.jar
    name: Executable JAR

deploy:
  # release: octane-gitlab-service-v$(appveyor_build_version)
  # description: 'Release description'
  provider: GitHub
  auth_token:
    secure: XLl9nRcYJQGot0rz4p/H3Brzkt1iGB9VqIQ0X/BMBGkhpeZzaRHfbLPcPsHCiGku # your encrypted token from GitHub
  artifact: /.*\.jar/            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only